
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javazoom.jl.decoder.JavaLayerException;
import javazoom.jl.player.Player;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ACER
 */
public class sem2 extends javax.swing.JFrame {
String tmark2,tmark3;

    /**
     * Creates new form sem1
     */
  public sem2() {
        initComponents();
        perc.setVisible(false);
      
 
      
       
      
    
         try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/db_cgpa","root","");
            String sql="SELECT totalmark FROM tblc WHERE id = 1";
            
            System.out.println(sql);
            Statement stmt=con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            
            if(rs.next())
            {
    int id = rs.getInt("totalmark");
    String s=String.valueOf(id);
          sem1t.setText(s);
            }
        }
        catch(Exception e)
        {
            System.out.println("error" + e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel29 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        perc = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        ec2S = new javax.swing.JTextField();
        em2S = new javax.swing.JTextField();
        ep2S = new javax.swing.JTextField();
        ech2S = new javax.swing.JTextField();
        pcS = new javax.swing.JTextField();
        egS = new javax.swing.JTextField();
        wpS = new javax.swing.JTextField();
        esl2S = new javax.swing.JTextField();
        pclS = new javax.swing.JTextField();
        lsS = new javax.swing.JTextField();
        progress = new javax.swing.JProgressBar();
        sem1totnew = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        sem1t = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        ls = new javax.swing.JTextField();
        pcl = new javax.swing.JTextField();
        wp = new javax.swing.JTextField();
        esl2 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        em2 = new javax.swing.JTextField();
        ec2 = new javax.swing.JTextField();
        ep2 = new javax.swing.JTextField();
        ech2 = new javax.swing.JTextField();
        pc = new javax.swing.JTextField();
        eg = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JButton();
        Cgpa = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        percentage1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        ec3 = new javax.swing.JTextField();

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/next.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        perc.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        perc.setForeground(new java.awt.Color(255, 255, 255));
        perc.setText("%");
        jPanel1.add(perc);
        perc.setBounds(893, 256, 50, 60);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText(" Grade");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(370, 90, 40, 16);

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("  Point");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(430, 90, 40, 16);

        ec2S.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ec2SFocusLost(evt);
            }
        });
        ec2S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ec2SActionPerformed(evt);
            }
        });
        ec2S.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ec2SKeyPressed(evt);
            }
        });
        jPanel1.add(ec2S);
        ec2S.setBounds(370, 110, 40, 30);

        em2S.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                em2SFocusLost(evt);
            }
        });
        em2S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                em2SActionPerformed(evt);
            }
        });
        em2S.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                em2SKeyPressed(evt);
            }
        });
        jPanel1.add(em2S);
        em2S.setBounds(370, 150, 40, 30);

        ep2S.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ep2SFocusLost(evt);
            }
        });
        ep2S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ep2SActionPerformed(evt);
            }
        });
        ep2S.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ep2SKeyPressed(evt);
            }
        });
        jPanel1.add(ep2S);
        ep2S.setBounds(370, 190, 40, 30);

        ech2S.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ech2SFocusLost(evt);
            }
        });
        ech2S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ech2SActionPerformed(evt);
            }
        });
        ech2S.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ech2SKeyPressed(evt);
            }
        });
        jPanel1.add(ech2S);
        ech2S.setBounds(370, 230, 40, 30);

        pcS.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pcSFocusLost(evt);
            }
        });
        pcS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcSActionPerformed(evt);
            }
        });
        pcS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pcSKeyPressed(evt);
            }
        });
        jPanel1.add(pcS);
        pcS.setBounds(370, 270, 40, 30);

        egS.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                egSFocusLost(evt);
            }
        });
        egS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                egSMouseClicked(evt);
            }
        });
        egS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                egSActionPerformed(evt);
            }
        });
        egS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                egSKeyPressed(evt);
            }
        });
        jPanel1.add(egS);
        egS.setBounds(370, 310, 40, 30);

        wpS.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                wpSFocusLost(evt);
            }
        });
        wpS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wpSActionPerformed(evt);
            }
        });
        wpS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                wpSKeyPressed(evt);
            }
        });
        jPanel1.add(wpS);
        wpS.setBounds(370, 350, 40, 30);

        esl2S.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                esl2SFocusLost(evt);
            }
        });
        esl2S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esl2SActionPerformed(evt);
            }
        });
        esl2S.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                esl2SKeyPressed(evt);
            }
        });
        jPanel1.add(esl2S);
        esl2S.setBounds(370, 390, 40, 30);

        pclS.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pclSFocusLost(evt);
            }
        });
        pclS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pclSActionPerformed(evt);
            }
        });
        pclS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pclSKeyPressed(evt);
            }
        });
        jPanel1.add(pclS);
        pclS.setBounds(370, 430, 40, 30);

        lsS.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lsSFocusLost(evt);
            }
        });
        lsS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lsSActionPerformed(evt);
            }
        });
        lsS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lsSKeyPressed(evt);
            }
        });
        jPanel1.add(lsS);
        lsS.setBounds(370, 470, 40, 30);

        progress.setMaximum(10);
        progress.setToolTipText("Your Progress");
        jPanel1.add(progress);
        progress.setBounds(530, 480, 270, 10);

        sem1totnew.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        sem1totnew.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(sem1totnew);
        sem1totnew.setBounds(220, 50, 110, 0);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/next.png"))); // NOI18N
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel24);
        jLabel24.setBounds(1070, 0, 165, 50);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.png"))); // NOI18N
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel23);
        jLabel23.setBounds(0, 0, 60, 60);

        sem1t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sem1tActionPerformed(evt);
            }
        });
        jPanel1.add(sem1t);
        sem1t.setBounds(770, 120, 100, 40);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("SEMESTER 1 TOTAL :");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(540, 120, 220, 40);

        ls.setEditable(false);
        ls.setAutoscrolls(false);
        ls.setEnabled(false);
        ls.setFocusable(false);
        ls.setRequestFocusEnabled(false);
        ls.setVerifyInputWhenFocusTarget(false);
        ls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lsActionPerformed(evt);
            }
        });
        ls.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lsKeyPressed(evt);
            }
        });
        jPanel1.add(ls);
        ls.setBounds(430, 470, 40, 30);

        pcl.setEditable(false);
        pcl.setAutoscrolls(false);
        pcl.setEnabled(false);
        pcl.setFocusable(false);
        pcl.setRequestFocusEnabled(false);
        pcl.setVerifyInputWhenFocusTarget(false);
        pcl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pclActionPerformed(evt);
            }
        });
        pcl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pclKeyPressed(evt);
            }
        });
        jPanel1.add(pcl);
        pcl.setBounds(430, 430, 40, 30);

        wp.setEditable(false);
        wp.setAutoscrolls(false);
        wp.setEnabled(false);
        wp.setFocusable(false);
        wp.setRequestFocusEnabled(false);
        wp.setVerifyInputWhenFocusTarget(false);
        wp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wpActionPerformed(evt);
            }
        });
        wp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                wpKeyPressed(evt);
            }
        });
        jPanel1.add(wp);
        wp.setBounds(430, 350, 40, 30);

        esl2.setEditable(false);
        esl2.setAutoscrolls(false);
        esl2.setEnabled(false);
        esl2.setFocusable(false);
        esl2.setRequestFocusEnabled(false);
        esl2.setVerifyInputWhenFocusTarget(false);
        esl2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esl2ActionPerformed(evt);
            }
        });
        esl2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                esl2KeyPressed(evt);
            }
        });
        jPanel1.add(esl2);
        esl2.setBounds(430, 390, 40, 30);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Life Skill :");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(290, 465, 80, 40);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Programming in C lab :");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(180, 415, 190, 60);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Engineering Science Lab II :");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(150, 370, 220, 70);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("English for Communication II :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(126, 94, 239, 60);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("English for Mathematics II :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(151, 141, 214, 50);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Engineering Physics II :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(186, 169, 179, 70);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText(" Workshop Practice :");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(200, 325, 170, 80);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Engineering Chemistry II :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(164, 216, 201, 60);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("                Programming in C :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(130, 240, 240, 90);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("      Engineering Graphics :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(155, 280, 220, 90);

        em2.setEditable(false);
        em2.setAutoscrolls(false);
        em2.setEnabled(false);
        em2.setFocusable(false);
        em2.setRequestFocusEnabled(false);
        em2.setVerifyInputWhenFocusTarget(false);
        em2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                em2ActionPerformed(evt);
            }
        });
        em2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                em2KeyPressed(evt);
            }
        });
        jPanel1.add(em2);
        em2.setBounds(430, 150, 40, 30);

        ec2.setEditable(false);
        ec2.setAutoscrolls(false);
        ec2.setEnabled(false);
        ec2.setFocusable(false);
        ec2.setRequestFocusEnabled(false);
        ec2.setVerifyInputWhenFocusTarget(false);
        ec2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ec2ActionPerformed(evt);
            }
        });
        ec2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ec2KeyPressed(evt);
            }
        });
        jPanel1.add(ec2);
        ec2.setBounds(430, 110, 40, 30);

        ep2.setEditable(false);
        ep2.setAutoscrolls(false);
        ep2.setEnabled(false);
        ep2.setFocusable(false);
        ep2.setRequestFocusEnabled(false);
        ep2.setVerifyInputWhenFocusTarget(false);
        ep2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ep2ActionPerformed(evt);
            }
        });
        ep2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ep2KeyPressed(evt);
            }
        });
        jPanel1.add(ep2);
        ep2.setBounds(430, 190, 40, 30);

        ech2.setEditable(false);
        ech2.setAutoscrolls(false);
        ech2.setEnabled(false);
        ech2.setFocusable(false);
        ech2.setRequestFocusEnabled(false);
        ech2.setVerifyInputWhenFocusTarget(false);
        ech2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ech2ActionPerformed(evt);
            }
        });
        ech2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ech2KeyPressed(evt);
            }
        });
        jPanel1.add(ech2);
        ech2.setBounds(430, 230, 40, 30);

        pc.setEditable(false);
        pc.setAutoscrolls(false);
        pc.setEnabled(false);
        pc.setFocusable(false);
        pc.setRequestFocusEnabled(false);
        pc.setVerifyInputWhenFocusTarget(false);
        pc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcActionPerformed(evt);
            }
        });
        pc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pcKeyPressed(evt);
            }
        });
        jPanel1.add(pc);
        pc.setBounds(430, 270, 40, 30);

        eg.setEditable(false);
        eg.setAutoscrolls(false);
        eg.setEnabled(false);
        eg.setFocusable(false);
        eg.setRequestFocusEnabled(false);
        eg.setVerifyInputWhenFocusTarget(false);
        eg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                egMouseClicked(evt);
            }
        });
        eg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                egActionPerformed(evt);
            }
        });
        eg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                egKeyPressed(evt);
            }
        });
        jPanel1.add(eg);
        eg.setBounds(430, 310, 40, 30);

        jToggleButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jToggleButton1.setText("CALCULATE");
        jToggleButton1.setToolTipText("Click to Calculate Your SEM CGPA");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1);
        jToggleButton1.setBounds(560, 410, 210, 50);

        Cgpa.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        Cgpa.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Cgpa);
        Cgpa.setBounds(770, 320, 390, 70);

        total.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        total.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(total);
        total.setBounds(770, 180, 260, 70);

        percentage1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        percentage1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(percentage1);
        percentage1.setBounds(770, 240, 120, 90);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("TOTAL MARK :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(510, 200, 260, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(" CGPA :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(640, 330, 140, 50);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("  PERCENTAGE :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(505, 250, 270, 70);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SEM2NEW.png"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, 0, 1240, 510);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("                Programming in C :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(130, 280, 240, 50);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("                Programming in C :");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(130, 280, 240, 50);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("      Engineering Graphics :");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(155, 320, 220, 50);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("      Engineering Graphics :");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(155, 320, 220, 50);

        jLabel15.setText("jLabel15");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(260, 360, 110, 80);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText(" Workshop Practice :");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(200, 380, 170, 25);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText(" Workshop Practice :");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(200, 380, 170, 25);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField5);
        jTextField5.setBounds(380, 470, 40, 30);

        ec3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ec3ActionPerformed(evt);
            }
        });
        ec3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ec3KeyPressed(evt);
            }
        });
        jPanel1.add(ec3);
        ec3.setBounds(380, 110, 40, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1236, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void em2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_em2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_em2ActionPerformed

    private void ec2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ec2ActionPerformed
     
    }//GEN-LAST:event_ec2ActionPerformed

    private void ep2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ep2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ep2ActionPerformed

    private void ech2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ech2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ech2ActionPerformed

    private void pcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pcActionPerformed

    private void egActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_egActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_egActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
             String ec2H, em2H, ep2H, ech2H, pcH, egH, wpH, esl2H, pclH, lsH, sem1tl;
        float average;
       float totalmark;
       float totalmark2;
       float totalmark3;
         float totalmark4;
       double percentage;
        float cgpa;
         float cgpa2;
        ec2H = ec2.getText();
        em2H = em2.getText();
        ep2H = ep2.getText();
        ech2H = ech2.getText();
     sem1tl = sem1t.getText();
        pcH = pc.getText();
      
        egH = eg.getText();
    wpH = wp.getText();
    
    esl2H = esl2.getText();
        pclH = pcl.getText();
        lsH = ls.getText();
                float ecgrade =Float.parseFloat(ec2H);
        float emgrade = Float.parseFloat(em2H);
        float epgrade = Float.parseFloat(ep2H);
        float echgrade = Float.parseFloat(ech2H);
      
        float pcgrade = Float.parseFloat(pcH);
     
        float eggrade = Float.parseFloat(egH);
        float wpgrade = Float.parseFloat(wpH);
        float eslgrade = Float.parseFloat(esl2H);
        float pclgrade = Float.parseFloat(pclH);
        float lsgrade = Float.parseFloat(lsH);
          float sem1tH = Float.parseFloat(sem1tl);
        totalmark = ((ecgrade*3) + (emgrade*6) + (epgrade*3) + (echgrade*3) + (pcgrade*4) + (eggrade*5) + (wpgrade*3) + (eslgrade*3) + (pclgrade*2) + (lsgrade*2));
       
        cgpa = (((ecgrade*3) + (emgrade*6) + (epgrade*3) + (echgrade*3) + (pcgrade*4) + (eggrade*5) + (wpgrade*3) + (eslgrade*3) + (pclgrade*2) + (lsgrade*2)) / 34);
         percentage = (cgpa*9.5);
  totalmark2 = (sem1tH + totalmark);
  
  totalmark3 = totalmark;
  totalmark4 = sem1tH;
  cgpa2 = (totalmark2 / 55);
  double rounded = Math.round(cgpa2*100)/100.0;
   
         double rounded2 = Math.round(percentage*100)/100.0;
        Cgpa.setText(rounded+"");
        total.setText(totalmark+"");
        percentage1.setText(rounded2+"");
          String cgpA = Cgpa.getText();
        System.out.println(cgpA);
    try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/db_cgpa","root","");
                String sql="UPDATE tblc SET cgpa=('"+cgpA+"') WHERE id = 2";
                System.out.println(sql);
                Statement stmt=con.createStatement();
                int rs = stmt.executeUpdate(sql);

            }
            catch(Exception e)
            {
                System.out.println("error" + e);
            }
        
            if(cgpa2 >= 8){
                                               try
       {
           FileInputStream fileInputStream = new FileInputStream("good.mp3");
           Player player = new Player(fileInputStream);
           player.play();
       }
       catch(FileNotFoundException | JavaLayerException e){
       
       }

        }
        else if(cgpa2 >= 5){
                                                try
       {
           FileInputStream fileInputStream = new FileInputStream("notbad.mp3");
           Player player = new Player(fileInputStream);
           player.play();
       }
       catch(FileNotFoundException | JavaLayerException e){
       
       }

        }
        else{
                                                try
       {
           FileInputStream fileInputStream = new FileInputStream("bad.mp3");
           Player player = new Player(fileInputStream);
           player.play();
       }
       catch(FileNotFoundException | JavaLayerException e){
       
       }

        }
            perc.setVisible(true);
         int i = (int) cgpa;
     
        for(i=1;i<=10;i++){
        progress.setValue((int) cgpa);
        }
       String sem1tot = total.getText();
        System.out.println(sem1tot);
   try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/db_cgpa","root","");
                String sql="UPDATE tblc SET totalmark=('"+sem1tot+"') WHERE id = 2";
                System.out.println(sql);
                Statement stmt=con.createStatement();
                int rs = stmt.executeUpdate(sql);

            }
            catch(Exception e)
            {
                System.out.println("error" + e);
            }
           



 try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/db_cgpa","root","");
                String sql="UPDATE tblc SET sum1 = (SELECT SUM(totalmark) as sum_i FROM tblc WHERE id < 3) where id =1";
                System.out.println(sql);
                Statement stmt=con.createStatement();
                int rs = stmt.executeUpdate(sql);

            }
            catch(Exception e)
            {
                System.out.println("error" + e);
            }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void wpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wpActionPerformed
        // TODO add your handlig code here:
    }//GEN-LAST:event_wpActionPerformed

    private void pclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pclActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pclActionPerformed

    private void esl2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esl2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_esl2ActionPerformed

    private void lsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lsActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void sem1tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sem1tActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sem1tActionPerformed

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        // TODO add your handling code here:
    dashboard p=new dashboard();
        p.setVisible(true);
          dispose();
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        // TODO add your handling code here:
           sem3 p=new sem3();
        p.setVisible(true);
          dispose();
    }//GEN-LAST:event_jLabel24MouseClicked

    private void ec2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ec2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        em2.requestFocusInWindow();
        }
    }//GEN-LAST:event_ec2KeyPressed

    private void em2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_em2KeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        ep2.requestFocusInWindow();
    }//GEN-LAST:event_em2KeyPressed
    }
    private void ep2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ep2KeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        ech2.requestFocusInWindow();
         }
    }//GEN-LAST:event_ep2KeyPressed

    private void ech2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ech2KeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        pc.requestFocusInWindow();
         }
    }//GEN-LAST:event_ech2KeyPressed

    private void pcKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pcKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        eg.requestFocusInWindow();
         }
    }//GEN-LAST:event_pcKeyPressed

    private void egMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_egMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_egMouseClicked

    private void egKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_egKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        wp.requestFocusInWindow();
         }
    }//GEN-LAST:event_egKeyPressed

    private void wpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wpKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        esl2.requestFocusInWindow();
         }
    }//GEN-LAST:event_wpKeyPressed

    private void esl2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_esl2KeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        pcl.requestFocusInWindow();
         }
    }//GEN-LAST:event_esl2KeyPressed

    private void pclKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pclKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        ls.requestFocusInWindow();
         }
    }//GEN-LAST:event_pclKeyPressed

    private void lsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lsKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        jToggleButton1.requestFocus(rootPaneCheckingEnabled);
         }
    }//GEN-LAST:event_lsKeyPressed

    private void ec3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ec3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ec3ActionPerformed

    private void ec3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ec3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ec3KeyPressed

    private void ec2SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ec2SActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ec2SActionPerformed

    private void ec2SKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ec2SKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ec2SKeyPressed

    private void em2SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_em2SActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_em2SActionPerformed

    private void em2SKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_em2SKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_em2SKeyPressed

    private void ep2SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ep2SActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ep2SActionPerformed

    private void ep2SKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ep2SKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ep2SKeyPressed

    private void ech2SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ech2SActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ech2SActionPerformed

    private void ech2SKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ech2SKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ech2SKeyPressed

    private void pcSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pcSActionPerformed

    private void pcSKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pcSKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_pcSKeyPressed

    private void egSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_egSMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_egSMouseClicked

    private void egSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_egSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_egSActionPerformed

    private void egSKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_egSKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_egSKeyPressed

    private void wpSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wpSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wpSActionPerformed

    private void wpSKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wpSKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_wpSKeyPressed

    private void esl2SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esl2SActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_esl2SActionPerformed

    private void esl2SKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_esl2SKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_esl2SKeyPressed

    private void pclSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pclSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pclSActionPerformed

    private void pclSKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pclSKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_pclSKeyPressed

    private void lsSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lsSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lsSActionPerformed

    private void lsSKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lsSKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lsSKeyPressed

    private void ec2SFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ec2SFocusLost
        // TODO add your handling code here:
                                             String i;
        i=ec2S.getText();
        
        if("S".equals(i)){
           
          ec2.setText("10");
        }
      if("A".equals(i)){
            
         ec2.setText("9");
        }
               if("B".equals(i)){
            
          ec2.setText("8");
        }
                   if("C".equals(i)){
            
          ec2.setText("7");
        }
                       if("D".equals(i)){
            
          ec2.setText("6");
        }
                           if("E".equals(i)){
            
          ec2.setText("5");
        }
                               if("F".equals(i)){
          
         ec2.setText("0");
        }
    }//GEN-LAST:event_ec2SFocusLost

    private void em2SFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_em2SFocusLost
        // TODO add your handling code here:
                                             String i;
        i=em2S.getText();
        
        if("S".equals(i)){
           
          em2.setText("10");
        }
      if("A".equals(i)){
            
           em2.setText("9");
        }
               if("B".equals(i)){
            
         em2.setText("8");
        }
                   if("C".equals(i)){
            
          em2.setText("7");
        }
                       if("D".equals(i)){
            
        em2.setText("6");
        }
                           if("E".equals(i)){
            
          em2.setText("5");
        }
                               if("F".equals(i)){
          
          em2.setText("0");
        }
    }//GEN-LAST:event_em2SFocusLost

    private void ep2SFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ep2SFocusLost
        // TODO add your handling code here:
                                             String i;
        i=ep2S.getText();
        
        if("S".equals(i)){
           
          ep2.setText("10");
        }
      if("A".equals(i)){
            
         ep2.setText("9");
        }
               if("B".equals(i)){
            
         ep2.setText("8");
        }
                   if("C".equals(i)){
            
         ep2.setText("7");
        }
                       if("D".equals(i)){
            
         ep2.setText("6");
        }
                           if("E".equals(i)){
            
           ep2.setText("5");
        }
                               if("F".equals(i)){
          
         ep2.setText("0");
        }
    }//GEN-LAST:event_ep2SFocusLost

    private void ech2SFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ech2SFocusLost
        // TODO add your handling code here:
                                             String i;
        i=ech2S.getText();
        
        if("S".equals(i)){
           
          ech2.setText("10");
        }
      if("A".equals(i)){
            
          ech2.setText("9");
        }
               if("B".equals(i)){
            
          ech2.setText("8");
        }
                   if("C".equals(i)){
            
          ech2.setText("7");
        }
                       if("D".equals(i)){
            
          ech2.setText("6");
        }
                           if("E".equals(i)){
            
         ech2.setText("5");
        }
                               if("F".equals(i)){
          
           ech2.setText("0");
        }
    }//GEN-LAST:event_ech2SFocusLost

    private void pcSFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pcSFocusLost
        // TODO add your handling code here:
                                             String i;
        i=pcS.getText();
        
        if("S".equals(i)){
           
         pc.setText("10");
        }
      if("A".equals(i)){
            
          pc.setText("9");
        }
               if("B".equals(i)){
            
          pc.setText("8");
        }
                   if("C".equals(i)){
            
          pc.setText("7");
        }
                       if("D".equals(i)){
            
          pc.setText("6");
        }
                           if("E".equals(i)){
            
          pc.setText("5");
        }
                               if("F".equals(i)){
          
          pc.setText("0");
        }
    }//GEN-LAST:event_pcSFocusLost

    private void egSFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_egSFocusLost
        // TODO add your handling code here:
                                             String i;
        i=egS.getText();
        
        if("S".equals(i)){
           
          eg.setText("10");
        }
      if("A".equals(i)){
            
           eg.setText("9");
        }
               if("B".equals(i)){
            
          eg.setText("8");
        }
                   if("C".equals(i)){
            
          eg.setText("7");
        }
                       if("D".equals(i)){
            
          eg.setText("6");
        }
                           if("E".equals(i)){
            
          eg.setText("5");
        }
                               if("F".equals(i)){
          
         eg.setText("0");
        }
    }//GEN-LAST:event_egSFocusLost

    private void wpSFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_wpSFocusLost
        // TODO add your handling code here:
                                             String i;
        i=wpS.getText();
        
        if("S".equals(i)){
           
           wp.setText("10");
        }
      if("A".equals(i)){
            
          wp.setText("9");
        }
               if("B".equals(i)){
            
         wp.setText("8");
        }
                   if("C".equals(i)){
            
          wp.setText("7");
        }
                       if("D".equals(i)){
            
          wp.setText("6");
        }
                           if("E".equals(i)){
            
          wp.setText("5");
        }
                               if("F".equals(i)){
          
         wp.setText("0");
        }
    }//GEN-LAST:event_wpSFocusLost

    private void esl2SFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_esl2SFocusLost
        // TODO add your handling code here:
                                             String i;
        i=esl2S.getText();
        
        if("S".equals(i)){
           
           esl2.setText("10");
        }
      if("A".equals(i)){
            
          esl2.setText("9");
        }
               if("B".equals(i)){
            
           esl2.setText("8");
        }
                   if("C".equals(i)){
            
           esl2.setText("7");
        }
                       if("D".equals(i)){
            
          esl2.setText("6");
        }
                           if("E".equals(i)){
            
           esl2.setText("5");
        }
                               if("F".equals(i)){
          
          esl2.setText("0");
        }
    }//GEN-LAST:event_esl2SFocusLost

    private void pclSFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pclSFocusLost
        // TODO add your handling code here:
                                             String i;
        i=pclS.getText();
        
        if("S".equals(i)){
           
           pcl.setText("10");
        }
      if("A".equals(i)){
            
           pcl.setText("9");
        }
               if("B".equals(i)){
            
           pcl.setText("8");
        }
                   if("C".equals(i)){
            
           pcl.setText("7");
        }
                       if("D".equals(i)){
            
           pcl.setText("6");
        }
                           if("E".equals(i)){
            
           pcl.setText("5");
        }
                               if("F".equals(i)){
          
           pcl.setText("0");
        }
    }//GEN-LAST:event_pclSFocusLost

    private void lsSFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lsSFocusLost
        // TODO add your handling code here:
                                             String i;
        i=lsS.getText();
        
        if("S".equals(i)){
           
           ls.setText("10");
        }
      if("A".equals(i)){
            
           ls.setText("9");
        }
               if("B".equals(i)){
            
           ls.setText("8");
        }
                   if("C".equals(i)){
            
           ls.setText("7");
        }
                       if("D".equals(i)){
            
           ls.setText("6");
        }
                           if("E".equals(i)){
            
           ls.setText("5");
        }
                               if("F".equals(i)){
          
           ls.setText("0");
        }
    }//GEN-LAST:event_lsSFocusLost
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sem1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sem1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sem1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sem1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sem2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cgpa;
    private javax.swing.JTextField ec2;
    private javax.swing.JTextField ec2S;
    private javax.swing.JTextField ec3;
    private javax.swing.JTextField ech2;
    private javax.swing.JTextField ech2S;
    private javax.swing.JTextField eg;
    private javax.swing.JTextField egS;
    private javax.swing.JTextField em2;
    private javax.swing.JTextField em2S;
    private javax.swing.JTextField ep2;
    private javax.swing.JTextField ep2S;
    private javax.swing.JTextField esl2;
    private javax.swing.JTextField esl2S;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JButton jToggleButton1;
    private javax.swing.JTextField ls;
    private javax.swing.JTextField lsS;
    private javax.swing.JTextField pc;
    private javax.swing.JTextField pcS;
    private javax.swing.JTextField pcl;
    private javax.swing.JTextField pclS;
    private javax.swing.JLabel perc;
    private javax.swing.JLabel percentage1;
    private javax.swing.JProgressBar progress;
    private javax.swing.JTextField sem1t;
    private javax.swing.JLabel sem1totnew;
    private javax.swing.JLabel total;
    private javax.swing.JTextField wp;
    private javax.swing.JTextField wpS;
    // End of variables declaration//GEN-END:variables
}
