

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *id = 1
 * @author ACER
 */
public class cgpa_cal extends javax.swing.JFrame {


    public cgpa_cal() {
        initComponents();
      
         try{
         Connection con=Database.connect();
            String sql="SELECT sem1,sem2,sem3,sem4,sem5,sem6 FROM tbl_main where username='"+Login.username+"'";
            
            System.out.println(sql);
            Statement stmt=con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            
            if(rs.next())
            {
               String sem1_sgpa=rs.getString("sem1");
               sem1.setText(sem1_sgpa);
               String sem2_sgpa=rs.getString("sem2");
               sem2.setText(sem2_sgpa);
               String sem3_sgpa=rs.getString("sem3");
               sem3.setText(sem3_sgpa);
               String sem4_sgpa=rs.getString("sem4");
               sem4.setText(sem4_sgpa);
               String sem5_sgpa=rs.getString("sem5");
               sem5.setText(sem5_sgpa);
               String sem6_sgpa=rs.getString("sem6");
               sem6.setText(sem6_sgpa);
               
            }
         }
            catch(Exception e)
            {
                System.out.println("error" + e);
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        result = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cgpacal = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        sem3 = new javax.swing.JTextField();
        sem6 = new javax.swing.JTextField();
        sem5 = new javax.swing.JTextField();
        sem4 = new javax.swing.JTextField();
        sem2 = new javax.swing.JTextField();
        sem1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1240, 518));
        jPanel1.setLayout(null);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(20, 20, 110, 50);

        reset.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel1.add(reset);
        reset.setBounds(560, 440, 90, 40);

        result.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        result.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(result);
        result.setBounds(870, 430, 130, 60);

        jLabel19.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("CGPA :");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(750, 440, 120, 40);

        cgpacal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cgpacal.setText("CALCULATE CGPA");
        cgpacal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cgpacalActionPerformed(evt);
            }
        });
        jPanel1.add(cgpacal);
        cgpacal.setBounds(220, 440, 220, 40);

        jLabel18.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("SEMESTER 2 :");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(490, 210, 160, 40);

        jLabel14.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("SEMESTER 5 :");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(490, 330, 160, 40);

        jLabel15.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("SEMESTER 6 :");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(820, 330, 160, 40);

        jLabel16.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("SEMESTER 3 :");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(820, 210, 160, 40);

        jLabel17.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("SEMESTER 4 :");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(140, 330, 160, 40);

        sem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sem3ActionPerformed(evt);
            }
        });
        sem3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sem3KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sem3KeyReleased(evt);
            }
        });
        jPanel1.add(sem3);
        sem3.setBounds(980, 210, 100, 40);

        sem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sem6ActionPerformed(evt);
            }
        });
        sem6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sem6KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sem6KeyReleased(evt);
            }
        });
        jPanel1.add(sem6);
        sem6.setBounds(980, 330, 100, 40);

        sem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sem5ActionPerformed(evt);
            }
        });
        sem5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sem5KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sem5KeyReleased(evt);
            }
        });
        jPanel1.add(sem5);
        sem5.setBounds(650, 330, 100, 40);

        sem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sem4ActionPerformed(evt);
            }
        });
        sem4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sem4KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sem4KeyReleased(evt);
            }
        });
        jPanel1.add(sem4);
        sem4.setBounds(300, 330, 100, 40);

        sem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sem2ActionPerformed(evt);
            }
        });
        sem2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sem2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sem2KeyReleased(evt);
            }
        });
        jPanel1.add(sem2);
        sem2.setBounds(650, 210, 100, 40);

        sem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sem1ActionPerformed(evt);
            }
        });
        sem1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sem1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sem1KeyReleased(evt);
            }
        });
        jPanel1.add(sem1);
        sem1.setBounds(300, 210, 100, 40);

        jLabel7.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SEMESTER 1 :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(140, 210, 160, 40);

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(" Connect Status");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(1140, 90, 100, 14);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Untitled-2.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(1150, 20, 70, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/power.png"))); // NOI18N
        jLabel2.setToolTipText("Turn Off");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 430, 60, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -4, 1240, 520);

        jLabel13.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("SEMESTER 1 :");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(170, 190, 160, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
            try{
           Connection con=Database.connect();
            String sql="SELECT tot_p FROM tbl_main where id = 1";
            
            System.out.println(sql);
            Statement stmt=con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            
            if(rs.next())
            {
   JOptionPane.showMessageDialog(null, "Database Connected");
            }
        }
        catch(Exception e)
        {
  
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
         try{
          Connection con=Database.connect();
            String sql="SELECT * FROM tbl_main";
            
            System.out.println(sql);
            Statement stmt=con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            
            if(rs.next())
            {
  JOptionPane.showMessageDialog(null, "Database Connected");
            }
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void sem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sem1ActionPerformed

    private void sem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sem5ActionPerformed

    private void sem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sem4ActionPerformed

    private void sem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sem2ActionPerformed

    private void sem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sem6ActionPerformed

    private void sem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sem3ActionPerformed

    private void cgpacalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cgpacalActionPerformed
        // TODO add your handling code here:
        if(sem1.getText().isEmpty()&&sem2.getText().isEmpty()&&sem3.getText().isEmpty()&&sem4.getText().isEmpty()&&sem5.getText().isEmpty()&&sem6.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Please Enter your SGPA");
    }
        else{
          if(sem1.getText().isEmpty())
            sem1.setText("0");
        if(sem2.getText().isEmpty())
            sem2.setText("0");
        if(sem3.getText().isEmpty())
            sem3.setText("0");
        if(sem4.getText().isEmpty())
            sem4.setText("0");
        if(sem5.getText().isEmpty())
            sem5.setText("0");
        if(sem6.getText().isEmpty())
            sem6.setText("0");
        double cgpa;
        int count=0;
       String sem1h,sem2h,sem3h,sem4h,sem5h,sem6h;
       
       sem1h= sem1.getText();
       sem2h= sem2.getText();
       sem3h= sem3.getText();
       sem4h= sem4.getText();
       sem5h= sem5.getText();
       sem6h= sem6.getText();
       
      
         float sem1g =Float.parseFloat(sem1h);
         float sem2g =Float.parseFloat(sem2h);
         float sem3g =Float.parseFloat(sem3h);
         float sem4g =Float.parseFloat(sem4h);
         float sem5g =Float.parseFloat(sem5h);
         float sem6g =Float.parseFloat(sem6h);
         if(sem1g!=0)
             count++;
         if(sem2g!=0)
             count++;
         if(sem3g!=0)
             count++;
         if(sem4g!=0)
             count++;
         if(sem5g!=0)
             count++;
         if(sem6g!=0)
             count++;
         cgpa =(sem1g+sem2g+sem3g+sem4g+sem5g+sem6g)/count;
          double rounded = Math.round(cgpa*100)/100.0;
          result.setText(rounded+"");
          try{
              Connection con=Database.connect();
                String sql="UPDATE tbl_main SET sem1=('"+sem1g+"'),sem2=('"+sem2g+"'),sem3=('"+sem3g+"'),sem4=('"+sem4g+"'),sem5=('"+sem5g+"'),sem6=('"+sem6g+"') WHERE username='"+Login.username+"'";
                System.out.println(sql);
                Statement stmt=con.createStatement();
                int rs = stmt.executeUpdate(sql);

            }
            catch(Exception e)
            {
                System.out.println("error" + e);
            }
        }
        
    }//GEN-LAST:event_cgpacalActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        sem1.setText("");
        sem2.setText("");
        sem3.setText("");
        sem4.setText("");
        sem5.setText("");
        sem6.setText("");
        
    }//GEN-LAST:event_resetActionPerformed

    private void sem1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sem1KeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_sem1KeyPressed

    private void sem2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sem2KeyPressed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_sem2KeyPressed

    private void sem3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sem3KeyReleased
        // TODO add your handling code here:
        String value =sem3.getText();
         String value3 =sem3.getText();
         int len=value.length();
       if(evt.getKeyChar()>='0'&&evt.getKeyChar()>'9'){
           JOptionPane.showMessageDialog(null, "Characters are not allowed");
           sem3.setText("");
       }
if(len<0||len>10){
   JOptionPane.showMessageDialog(null, "SGPA must be between 1 and 10");
 sem3.setText("");
           }
    }//GEN-LAST:event_sem3KeyReleased

    private void sem3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sem3KeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_sem3KeyPressed

    private void sem4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sem4KeyPressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_sem4KeyPressed

    private void sem5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sem5KeyPressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_sem5KeyPressed

    private void sem6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sem6KeyPressed
    
    }//GEN-LAST:event_sem6KeyPressed

    private void sem6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sem6KeyReleased
  String value =sem6.getText();
         String value3 =sem6.getText();
         int len=value.length();
       if(evt.getKeyChar()>='0'&&evt.getKeyChar()>'9'){
           JOptionPane.showMessageDialog(null, "Characters are not allowed");
           sem6.setText("");
       }
 else if(len>=1){
         
           float sem0 =Float.parseFloat(value3);
            
           if(sem0<0||sem0>10){
   JOptionPane.showMessageDialog(null, "SGPA must be between 1 and 10");
 sem6.setText("");
           }
 }
    }//GEN-LAST:event_sem6KeyReleased

    private void sem5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sem5KeyReleased
   String value =sem5.getText();
         String value3 =sem5.getText();
         int len=value.length();
       if(evt.getKeyChar()>='0'&&evt.getKeyChar()>'9'){
           JOptionPane.showMessageDialog(null, "Characters are not allowed");
           sem5.setText("");
       }
      
 else if(len>=1){
         
           float sem0 =Float.parseFloat(value3);
            
           if(sem0<0||sem0>10){
   JOptionPane.showMessageDialog(null, "SGPA must be between 1 and 10");
 sem5.setText("");
           }
           }
    }//GEN-LAST:event_sem5KeyReleased

    private void sem4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sem4KeyReleased
        // TODO add your handling code here:
        String value =sem4.getText();
         String value3 =sem4.getText();
         int len=value.length();
       if(evt.getKeyChar()>='0'&&evt.getKeyChar()>'9'){
           JOptionPane.showMessageDialog(null, "Characters are not allowed");
           sem4.setText("");
       }
 else if(len>=1){
         
           float sem0 =Float.parseFloat(value3);
            
           if(sem0<0||sem0>10){
   JOptionPane.showMessageDialog(null, "SGPA must be between 1 and 10");
 sem4.setText("");
           }
 }
    }//GEN-LAST:event_sem4KeyReleased

    private void sem2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sem2KeyReleased
        // TODO add your handling code here:
        String value =sem2.getText();
         String value3 =sem2.getText();
         int len=value.length();
       if(evt.getKeyChar()>='0'&&evt.getKeyChar()>'9'){
           JOptionPane.showMessageDialog(null, "Characters are not allowed");
           sem2.setText("");
       }
       else if(len>=1){
         
           float sem0 =Float.parseFloat(value3);
            
           if(sem0<0||sem0>10){
               
   JOptionPane.showMessageDialog(null, "SGPA must be between 1 and 10");
 sem2.setText("");
           }
           }
    }//GEN-LAST:event_sem2KeyReleased

    private void sem1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sem1KeyReleased
        // TODO add your handling code here:
        String value =sem1.getText();
         String value3 =sem1.getText();
         int len=value.length();
       if(evt.getKeyChar()>='0'&&evt.getKeyChar()>'9'){
           JOptionPane.showMessageDialog(null, "Characters are not allowed");
           sem1.setText("");
       }
 else if(len>=1){
         
           float sem0 =Float.parseFloat(value3);
            
           if(sem0<0||sem0>10){
   JOptionPane.showMessageDialog(null, "SGPA must be between 1 and 10");
 sem1.setText("");
           }
 }
    }//GEN-LAST:event_sem1KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
     choice p=new choice();
        p.setVisible(true);
          dispose(); 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
 
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cgpa_cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cgpa_cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cgpa_cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cgpa_cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cgpa_cal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cgpacal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton reset;
    private javax.swing.JLabel result;
    private javax.swing.JTextField sem1;
    private javax.swing.JTextField sem2;
    private javax.swing.JTextField sem3;
    private javax.swing.JTextField sem4;
    private javax.swing.JTextField sem5;
    private javax.swing.JTextField sem6;
    // End of variables declaration//GEN-END:variables
}
