

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *id = 1
 * @author ACER
 */
public class dashboard extends javax.swing.JFrame {
int value;

    /**
     * Creates new form dashboard
     */
    public dashboard() {
          
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
         try{
            Connection con=Database.connect();
            String sql="SELECT * FROM tbl_main WHERE username='"+Login.username+"'";
            
            System.out.println(sql);
            Statement stmt=con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
         
            if(rs.next())
            {
    int value = rs.getInt("checkbox");
   
  if(value == 1){
          
             sem1.setVisible(false);
               sem2.setVisible(false);
               check.doClick();
               
           
       
    float id = rs.getFloat("tot_cgpal");
 double rounded = Math.round(id*100)/100.0;
    
      progress.setValue((int) id);  
    String s=String.valueOf(rounded);
          cgpa.setText(s);
            
         int point = rs.getInt("tot_pl");
     progress2.setValue(point); 
    String points=String.valueOf(point);
          tmark.setText(points);
  }
     else{
               sem1.setVisible(true);
               sem2.setVisible(true);
               progress2.setVisible(false);
               
          
    float cgpas = rs.getFloat("tot_cgpa");
    double roundedcgpa = Math.round(cgpas*100)/100.0;
    progress.setValue((int) cgpas); 
    String scgpa=String.valueOf(roundedcgpa);
          cgpa.setText(scgpa);
            
   
    int id = rs.getInt("tot_p");
     progress1.setValue(id); 
    String s=String.valueOf(id);
          tmark.setText(s);
            
        
      
         }

            }
         }
            
        
         
        catch(Exception e)
        {
            System.out.println("error" + e);
        }
     
       
    
                    
        
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        user = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        progress2 = new javax.swing.JProgressBar();
        progress1 = new javax.swing.JProgressBar();
        progress = new javax.swing.JProgressBar();
        tmark = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        check = new javax.swing.JCheckBox();
        cgpa = new javax.swing.JLabel();
        sem3 = new javax.swing.JLabel();
        sem2 = new javax.swing.JLabel();
        sem6 = new javax.swing.JLabel();
        sem4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sem1 = new javax.swing.JLabel();
        sem5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 708));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SELECT DESIRED SEMESTER");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(470, 10, 470, 60);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(1300, 20, 50, 50);

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(" Connection");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(1290, 70, 70, 14);

        logout.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        logout.setText("LOGOUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel1.add(logout);
        logout.setBounds(30, 650, 80, 23);

        user.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        user.setForeground(new java.awt.Color(242, 242, 242));
        user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/face.png"))); // NOI18N
        user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userMouseClicked(evt);
            }
        });
        jPanel1.add(user);
        user.setBounds(1290, 630, 50, 60);

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton4.setText("  BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(-20, -11, 120, 50);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("CLEAR DATA");
        jButton2.setToolTipText("Click after changing from LET to Normal and vice-versa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(30, 420, 150, 27);

        progress2.setMaximum(1200);
        progress2.setToolTipText("Your Progress");
        jPanel1.add(progress2);
        progress2.setBounds(680, 630, 400, 10);

        progress1.setMaximum(1750);
        progress1.setToolTipText("Your Progress");
        jPanel1.add(progress1);
        progress1.setBounds(680, 630, 400, 10);

        progress.setMaximum(10);
        progress.setToolTipText("Your Progress");
        jPanel1.add(progress);
        progress.setBounds(220, 630, 220, 10);

        tmark.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        tmark.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(tmark);
        tmark.setBounds(1090, 570, 120, 70);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" TOTAL GRADE POINTS :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(670, 590, 420, 30);

        check.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        check.setForeground(new java.awt.Color(255, 255, 255));
        check.setText("LET");
        check.setToolTipText("Click Here if You are a Lateral Entry Student");
        check.setBorder(new javax.swing.border.MatteBorder(null));
        check.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        check.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkMouseClicked(evt);
            }
        });
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });
        jPanel1.add(check);
        check.setBounds(50, 210, 110, 50);
        check.getAccessibleContext().setAccessibleDescription("hi");

        cgpa.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        cgpa.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(cgpa);
        cgpa.setBounds(450, 570, 180, 70);

        sem3.setBackground(new java.awt.Color(0, 0, 0));
        sem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ISEM3.png"))); // NOI18N
        sem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sem3MouseClicked(evt);
            }
        });
        jPanel1.add(sem3);
        sem3.setBounds(930, 170, 280, 127);

        sem2.setBackground(new java.awt.Color(0, 0, 0));
        sem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ISEM2.png"))); // NOI18N
        sem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sem2MouseClicked(evt);
            }
        });
        jPanel1.add(sem2);
        sem2.setBounds(570, 170, 280, 127);

        sem6.setBackground(new java.awt.Color(0, 0, 0));
        sem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ISEM6.png"))); // NOI18N
        sem6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sem6MouseClicked(evt);
            }
        });
        jPanel1.add(sem6);
        sem6.setBounds(930, 370, 280, 127);

        sem4.setBackground(new java.awt.Color(0, 0, 0));
        sem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ISEM4.png"))); // NOI18N
        sem4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sem4MouseClicked(evt);
            }
        });
        jPanel1.add(sem4);
        sem4.setBounds(220, 370, 280, 130);

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("FINAL CGPA :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(220, 580, 240, 50);

        sem1.setBackground(new java.awt.Color(0, 0, 0));
        sem1.setForeground(new java.awt.Color(255, 255, 255));
        sem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ISEM1.png"))); // NOI18N
        sem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sem1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sem1MousePressed(evt);
            }
        });
        jPanel1.add(sem1);
        sem1.setBounds(220, 170, 280, 130);

        sem5.setBackground(new java.awt.Color(0, 0, 0));
        sem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ISEM5.png"))); // NOI18N
        sem5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sem5MouseClicked(evt);
            }
        });
        jPanel1.add(sem5);
        sem5.setBounds(570, 370, 280, 130);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -4, 1370, 710);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sem2MouseClicked
        // TODO add your handling code here:
 
                sem2 p=new sem2();
        p.setVisible(true);
          dispose();        
        
     
    }//GEN-LAST:event_sem2MouseClicked

    private void sem3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sem3MouseClicked
        // TODO add your handling code here:
 
        sem3 p=new sem3();
        p.setVisible(true);
          dispose();
    }//GEN-LAST:event_sem3MouseClicked

    private void sem5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sem5MouseClicked
        // TODO add your handling code here:
      
            sem5 p=new sem5();
        p.setVisible(true);
       
    }//GEN-LAST:event_sem5MouseClicked

    private void sem6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sem6MouseClicked
        // TODO add your handling code here:
    
            sem6 p=new sem6();
        p.setVisible(true);
          dispose();
    }//GEN-LAST:event_sem6MouseClicked

    private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_checkActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       try{
           int flag=0;
          Connection con=Database.connect();
                String sql="UPDATE tbl_main SET tot_cgpa = NULL,tot_cgpal=NULL,tot_p=NULL,tot_pl=NULL,sem1_p=NULL,sem2_p=NULL,sem3_p=NULL,sem4_p=NULL,sem5_p=NULL,sem6_p=NULL,sem3_pl=NULL,sem4_pl=NULL,sem5_pl=NULL,sem6_pl=NULL";
             
                System.out.println(sql);
             
                Statement stmt=con.createStatement();
                int rs = stmt.executeUpdate(sql);
            
                flag=1;
                if(flag==1)
                 JOptionPane.showMessageDialog(null, "Data cleared");
                    
                

            }
            catch(Exception e)
            {
              JOptionPane.showMessageDialog(null, "Error clearing Data");
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void sem4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sem4MouseClicked
        // TODO add your handling code here:

        sem4 p=new sem4();
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_sem4MouseClicked

    private void sem1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sem1MousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_sem1MousePressed

    private void sem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sem1MouseClicked
        // TODO add your handling code here:

        sem1 p=new sem1();
        p.setVisible(true);
        dispose();

    }//GEN-LAST:event_sem1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:

       checkconn.checkConnection();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
         checkconn.checkConnection();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        Login.username="";
        Login p=new Login();
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseClicked
        user p=new user();
        p.setVisible(true);
    }//GEN-LAST:event_userMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        choice1 p=new choice1();
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void checkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkMouseClicked
        // TODO add your handling code here:
         if(check.isSelected()){
             sem1.setVisible(false);
               sem2.setVisible(false);
               
               
                try{
                Connection con=Database.connect();
                String sql="UPDATE tbl_main SET checkbox=1 WHERE username='"+Login.username+"'";
                System.out.println(sql);
                Statement stmt=con.createStatement();
                int rs = stmt.executeUpdate(sql);

            }
            catch(Exception e)
            {
                System.out.println("error" + e);
            }
          }
          else{
              try{
                Connection con=Database.connect();
                String sql="UPDATE tbl_main SET checkbox=0 WHERE username='"+Login.username+"'";
                System.out.println(sql);
                Statement stmt=con.createStatement();
                int rs = stmt.executeUpdate(sql);

            }
            catch(Exception e)
            {
                System.out.println("error" + e);
            }
          }
          try{
            Connection con=Database.connect();
            String sql="SELECT * FROM tbl_main WHERE username='"+Login.username+"'";
            
            System.out.println(sql);
            Statement stmt=con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            
            if(rs.next())
            {
                 if(check.isSelected()){
    float id = rs.getFloat("tot_cgpal");
     double rounded = Math.round(id*100)/100.0;
    String s=String.valueOf(rounded);
          cgpa.setText(s);
             int point = rs.getInt("tot_pl");
    String points=String.valueOf(point);
          tmark.setText(points);
                 }
                  else{
               sem1.setVisible(true);
               sem2.setVisible(true);
               
         
    float id = rs.getFloat("tot_cgpa");
     double rounded = Math.round(id*100)/100.0;
    String s=String.valueOf(rounded);
          cgpa.setText(s);
            
      
           
    int point = rs.getInt("tot_p");
    String points=String.valueOf(point);
          tmark.setText(points);
        
            }
            
        }
          }
        catch(Exception e)
        {
            System.out.println("error" + e);
        }
                    
        
      
    }//GEN-LAST:event_checkMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
 
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cgpa;
    private javax.swing.JCheckBox check;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logout;
    private javax.swing.JProgressBar progress;
    private javax.swing.JProgressBar progress1;
    private javax.swing.JProgressBar progress2;
    private javax.swing.JLabel sem1;
    private javax.swing.JLabel sem2;
    private javax.swing.JLabel sem3;
    private javax.swing.JLabel sem4;
    private javax.swing.JLabel sem5;
    private javax.swing.JLabel sem6;
    private javax.swing.JLabel tmark;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
