import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ACER
 */
public class sem3 extends javax.swing.JFrame {
int value;
    /**
     * Creates new form sem1
     */
  public sem3() {
      
        initComponents();
      perc.setVisible(false);
       setExtendedState(JFrame.MAXIMIZED_BOTH);
      try{
          
             Connection con=Database.connect();
            String sql="SELECT * FROM tbl_main WHERE username='"+Login.username+"'";
            
            System.out.println(sql);
            Statement stmt=con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            
            if(rs.next())
            {
    int id = rs.getInt("checkbox");
    value=id;
    if(value == 1){
          
 sem1t.setVisible(false);
  sem1t2.setVisible(false);
  sem1tl.setVisible(false);
  sem1t2l.setVisible(false);
  check.doClick();
      }
    else{
               sem1t.setVisible(true);
               sem1t2.setVisible(true);
               sem1tl.setVisible(true);
               sem1t2l.setVisible(true);
                  int sem1 = rs.getInt("sem1_p");
                    String s1 = String.valueOf(sem1);
                    sem1t.setText(s1);
  int sem2 = rs.getInt("sem2_p");
                    String s2 = String.valueOf(sem2);
                    sem1t2.setText(s2);
      
      }
 
            }
        }
        catch(Exception e)
        {
            System.out.println("error" + e);
        }
    
    }
 



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        perc = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        dcp1 = new javax.swing.JTextField();
        ca1 = new javax.swing.JTextField();
        esdm1 = new javax.swing.JTextField();
        oopl1 = new javax.swing.JTextField();
        dbmsl1 = new javax.swing.JTextField();
        dcpl1 = new javax.swing.JTextField();
        dbms1 = new javax.swing.JTextField();
        oop1 = new javax.swing.JTextField();
        progress = new javax.swing.JProgressBar();
        jLabel22 = new javax.swing.JLabel();
        check = new javax.swing.JCheckBox();
        jLabel21 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        sem1t2 = new javax.swing.JTextField();
        sem1t2l = new javax.swing.JLabel();
        sem1tl = new javax.swing.JLabel();
        sem1t = new javax.swing.JTextField();
        oopl = new javax.swing.JTextField();
        dbmsl = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        oop = new javax.swing.JTextField();
        dcp = new javax.swing.JTextField();
        ca = new javax.swing.JTextField();
        dbms = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        esdm = new javax.swing.JTextField();
        dcpl = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JButton();
        Cgpa1 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        percentage1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 708));
        jPanel1.setLayout(null);

        perc.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        perc.setForeground(new java.awt.Color(255, 255, 255));
        perc.setText("%");
        jPanel1.add(perc);
        perc.setBounds(1080, 290, 50, 60);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText(" Grade");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(390, 120, 40, 16);

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("  Point");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(450, 120, 40, 16);

        dcp1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dcp1FocusLost(evt);
            }
        });
        dcp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dcp1ActionPerformed(evt);
            }
        });
        dcp1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dcp1KeyReleased(evt);
            }
        });
        jPanel1.add(dcp1);
        dcp1.setBounds(390, 140, 40, 30);

        ca1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ca1FocusLost(evt);
            }
        });
        ca1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ca1ActionPerformed(evt);
            }
        });
        ca1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ca1KeyReleased(evt);
            }
        });
        jPanel1.add(ca1);
        ca1.setBounds(390, 250, 40, 30);

        esdm1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                esdm1FocusLost(evt);
            }
        });
        esdm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esdm1ActionPerformed(evt);
            }
        });
        esdm1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                esdm1KeyReleased(evt);
            }
        });
        jPanel1.add(esdm1);
        esdm1.setBounds(390, 370, 40, 30);

        oopl1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                oopl1FocusLost(evt);
            }
        });
        oopl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oopl1ActionPerformed(evt);
            }
        });
        oopl1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                oopl1KeyReleased(evt);
            }
        });
        jPanel1.add(oopl1);
        oopl1.setBounds(390, 490, 40, 30);

        dbmsl1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dbmsl1FocusLost(evt);
            }
        });
        dbmsl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbmsl1ActionPerformed(evt);
            }
        });
        dbmsl1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dbmsl1KeyReleased(evt);
            }
        });
        jPanel1.add(dbmsl1);
        dbmsl1.setBounds(390, 550, 40, 30);

        dcpl1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dcpl1FocusLost(evt);
            }
        });
        dcpl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dcpl1ActionPerformed(evt);
            }
        });
        dcpl1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dcpl1KeyReleased(evt);
            }
        });
        jPanel1.add(dcpl1);
        dcpl1.setBounds(390, 430, 40, 30);

        dbms1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dbms1FocusLost(evt);
            }
        });
        dbms1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbms1ActionPerformed(evt);
            }
        });
        dbms1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dbms1KeyReleased(evt);
            }
        });
        jPanel1.add(dbms1);
        dbms1.setBounds(390, 310, 40, 30);

        oop1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                oop1FocusLost(evt);
            }
        });
        oop1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oop1ActionPerformed(evt);
            }
        });
        oop1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                oop1KeyReleased(evt);
            }
        });
        jPanel1.add(oop1);
        oop1.setBounds(390, 190, 40, 30);

        progress.setMaximum(10);
        progress.setToolTipText("Your Progress");
        jPanel1.add(progress);
        progress.setBounds(690, 580, 270, 10);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("ARE YOU LET STUDENT ?");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(220, 630, 220, 16);

        check.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        check.setForeground(new java.awt.Color(255, 255, 255));
        check.setText("YES");
        check.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkStateChanged(evt);
            }
        });
        check.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkMouseClicked(evt);
            }
        });
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });
        jPanel1.add(check);
        check.setBounds(440, 620, 100, 40);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NEXT2.png"))); // NOI18N
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel21);
        jLabel21.setBounds(1240, 10, 119, 63);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BACK2.png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel16);
        jLabel16.setBounds(10, 10, 119, 63);

        sem1t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sem1t2ActionPerformed(evt);
            }
        });
        jPanel1.add(sem1t2);
        sem1t2.setBounds(1080, 120, 100, 40);

        sem1t2l.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sem1t2l.setForeground(new java.awt.Color(255, 255, 255));
        sem1t2l.setText("SEM2 GRADE POINTS:");
        jPanel1.add(sem1t2l);
        sem1t2l.setBounds(890, 120, 180, 40);

        sem1tl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sem1tl.setForeground(new java.awt.Color(255, 255, 255));
        sem1tl.setText("SEM1 GRADE POINTS:");
        jPanel1.add(sem1tl);
        sem1tl.setBounds(560, 120, 177, 40);

        sem1t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sem1tActionPerformed(evt);
            }
        });
        jPanel1.add(sem1t);
        sem1t.setBounds(740, 120, 100, 40);

        oopl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ooplActionPerformed(evt);
            }
        });
        jPanel1.add(oopl);
        oopl.setBounds(450, 490, 40, 30);

        dbmsl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbmslActionPerformed(evt);
            }
        });
        jPanel1.add(dbmsl);
        dbmsl.setBounds(450, 550, 40, 30);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Database Management System Lab :");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(90, 530, 300, 70);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Digital Computer Principles :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(160, 120, 230, 60);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Object Oriented Programming through C++ :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 180, 360, 50);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Computer Architecture :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(200, 230, 190, 70);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Object Oriented Programming Lab :");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(100, 460, 290, 80);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Database Management System :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(130, 290, 260, 60);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ES&DM :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(310, 340, 80, 90);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Digital Computer Principles Lab :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(130, 400, 270, 90);

        oop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oopActionPerformed(evt);
            }
        });
        jPanel1.add(oop);
        oop.setBounds(450, 190, 40, 30);

        dcp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dcpActionPerformed(evt);
            }
        });
        jPanel1.add(dcp);
        dcp.setBounds(450, 140, 40, 30);

        ca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caActionPerformed(evt);
            }
        });
        jPanel1.add(ca);
        ca.setBounds(450, 250, 40, 30);

        dbms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbmsActionPerformed(evt);
            }
        });
        jPanel1.add(dbms);
        dbms.setBounds(450, 310, 40, 30);

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("SEMESTER 3");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(560, 20, 280, 70);

        esdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esdmActionPerformed(evt);
            }
        });
        jPanel1.add(esdm);
        esdm.setBounds(450, 370, 40, 30);

        dcpl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dcplActionPerformed(evt);
            }
        });
        jPanel1.add(dcpl);
        dcpl.setBounds(450, 430, 40, 30);

        jToggleButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jToggleButton1.setText("CALCULATE");
        jToggleButton1.setToolTipText("Click to Calculate Your SEM CGPA");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1);
        jToggleButton1.setBounds(720, 510, 210, 50);

        Cgpa1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        Cgpa1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Cgpa1);
        Cgpa1.setBounds(960, 390, 110, 70);

        total.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        total.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(total);
        total.setBounds(960, 180, 260, 70);

        percentage1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        percentage1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(percentage1);
        percentage1.setBounds(950, 270, 120, 90);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(" GRADE POINTS :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(660, 200, 300, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(" CGPA :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(830, 400, 140, 50);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("  PERCENTAGE :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(690, 280, 270, 70);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SEM.png"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, 0, 1370, 710);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("                Programming in C :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(130, 320, 240, 50);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("                Programming in C :");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(130, 320, 240, 50);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("      Engineering Graphics :");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(160, 360, 220, 50);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("      Engineering Graphics :");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(160, 360, 220, 50);

        jLabel15.setText("jLabel15");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(260, 400, 110, 80);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText(" Workshop Practice :");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(200, 420, 170, 25);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText(" Workshop Practice :");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(200, 420, 170, 25);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField5);
        jTextField5.setBounds(380, 510, 40, 30);

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("SEMESTER 1 TOTAL :");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(440, 160, 220, 40);

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("SEMESTER 1 TOTAL :");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(440, 160, 220, 40);

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText(" CGPA :");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(640, 330, 140, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void oopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oopActionPerformed

    private void dcpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dcpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dcpActionPerformed

    private void caActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caActionPerformed

    private void dbmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbmsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dbmsActionPerformed

    private void esdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esdmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_esdmActionPerformed

    private void dcplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dcplActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dcplActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
         if(dcp1.getText().isEmpty()||oop1.getText().isEmpty()||ca1.getText().isEmpty()||dbms1.getText().isEmpty()||esdm1.getText().isEmpty()||dcpl1.getText().isEmpty()||oopl1.getText().isEmpty()||dbmsl1.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Fill Grades correctly");
      }
      else{
          if(value == 1){
              
               String dcpH, oopH, caH, dbmsH, esdmH, dcplH, ooplH, dbmslH;
    
       float totalmark;
  
       double percentage;
        float cgpa;
         float cgpa2;
        
        dcpH = dcp.getText();
        oopH = oop.getText();
        caH = ca.getText();
        dbmsH = dbms.getText();
     
        esdmH = esdm.getText();
      
        dcplH = dcpl.getText();
    ooplH = oopl.getText();
    
    dbmslH = dbmsl.getText();
    
     
     
        float dcpgrade =Float.parseFloat(dcpH);
        float oopgrade = Float.parseFloat(oopH);
        float cagrade = Float.parseFloat(caH);
        float dbmsgrade = Float.parseFloat(dbmsH);
      
        float esdmgrade = Float.parseFloat(esdmH);
     
        float dcplgrade = Float.parseFloat(dcplH);
        float ooplgrade = Float.parseFloat(ooplH);
        float dbmslgrade = Float.parseFloat(dbmslH);
   
     
 
        totalmark = ((dcpgrade*4) + (oopgrade*5) + (cagrade*4) + (dbmsgrade*4) + (esdmgrade*3) + (dcplgrade*3) + (ooplgrade*3) + (dbmslgrade*3));
       
        cgpa = (((dcpgrade*4) + (oopgrade*5) + (cagrade*4) + (dbmsgrade*4) + (esdmgrade*3) + (dcplgrade*3) + (ooplgrade*3) + (dbmslgrade*3)) / 29);
     

  
  cgpa2 = (totalmark / 29);
   percentage = (cgpa2*9.5);
    double rounded = Math.round(cgpa2*100)/100.0;
   
         double rounded2 = Math.round(percentage*100)/100.0;
        Cgpa1.setText(rounded+"");
        
        total.setText(totalmark+"");
        percentage1.setText(rounded2+"");
          String cgpA = Cgpa1.getText();
        System.out.println(cgpA);
   
            
            perc.setVisible(true);
               int i = (int) cgpa2;
     
     
        progress.setValue(i);
        
           String sem1tot = total.getText();
        System.out.println(sem1tot);
         try{
                 Connection con=Database.connect();
                String sql="UPDATE tbl_main SET tot_cgpal=('"+cgpA+"'),sem3_pl=('"+sem1tot+"'),tot_pl = sem3_pl, WHERE username='"+Login.username+"'";
                System.out.println(sql);
                Statement stmt=con.createStatement();
                int rs = stmt.executeUpdate(sql);

            }
            catch(Exception e)
            {
                System.out.println("error" + e);
            }
  
          }
          else{
            String dcpH, oopH, caH, dbmsH, esdmH, dcplH, ooplH, dbmslH, sem1tL,sem2tL;
        float average;
       float totalmark;
       float totalmark2;
        float totalmark12;
         float totalmark13;
       double percentage;
       float gpa;
        float cgpa;
         float cgpa2;
        
        dcpH = dcp.getText();
        oopH = oop.getText();
        caH = ca.getText();
        dbmsH = dbms.getText();
     
        esdmH = esdm.getText();
      
        dcplH = dcpl.getText();
    ooplH = oopl.getText();
    
    dbmslH = dbmsl.getText();
      sem1tL = sem1t.getText();
      sem2tL = sem1t2.getText();
     
     
        float dcpgrade =Float.parseFloat(dcpH);
        float oopgrade = Float.parseFloat(oopH);
        float cagrade = Float.parseFloat(caH);
        float dbmsgrade = Float.parseFloat(dbmsH);
      
        float esdmgrade = Float.parseFloat(esdmH);
     
        float dcplgrade = Float.parseFloat(dcplH);
        float ooplgrade = Float.parseFloat(ooplH);
        float dbmslgrade = Float.parseFloat(dbmslH);
        float sem1tH = Float.parseFloat(sem1tL);
        float sem1tH2 = Float.parseFloat(sem2tL);
     
 
        totalmark = ((dcpgrade*4) + (oopgrade*5) + (cagrade*4) + (dbmsgrade*4) + (esdmgrade*3) + (dcplgrade*3) + (ooplgrade*3) + (dbmslgrade*3));
       
        cgpa = (((dcpgrade*4) + (oopgrade*5) + (cagrade*4) + (dbmsgrade*4) + (esdmgrade*3) + (dcplgrade*3) + (ooplgrade*3) + (dbmslgrade*3)) / 29);
        
  totalmark2 = (sem1tH + totalmark + sem1tH2);
  gpa=(((dcpgrade*4) + (oopgrade*5) + (cagrade*3) + (dbmsgrade*4) + (esdmgrade*3) + (dcplgrade*3) + (ooplgrade*3) + (dbmslgrade*3)) / 29);
  cgpa2 = (totalmark2 / 84);
   percentage = (cgpa2*9.5);
    double rounded = Math.round(cgpa2*100)/100.0;
     double rgpa = Math.round(cgpa*100)/100.0;

   
         double rounded2 = Math.round(percentage*100)/100.0;
        Cgpa1.setText(rounded+"");
   
        total.setText(totalmark+"");
        percentage1.setText(rounded2+"");
          String cgpA = Cgpa1.getText();
        System.out.println(cgpA);
        
    
           
            perc.setVisible(true);
               int j = (int) cgpa2;
     
   
        progress.setValue(j);
        
           String sem1tot = total.getText();
        System.out.println(sem1tot);
        try{
              Connection con=Database.connect();
                String sql="UPDATE tbl_main SET tot_cgpa=('"+cgpA+"'),sem3_p=('"+sem1tot+"'),tot_p = sem1_p+sem2_p+sem3_p WHERE username='"+Login.username+"'";
                System.out.println(sql);
                Statement stmt=con.createStatement();
                int rs = stmt.executeUpdate(sql);

            }
            catch(Exception e)
            {
                System.out.println("error" + e);
            }
          }
         }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void ooplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ooplActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ooplActionPerformed

    private void dbmslActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbmslActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dbmslActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void sem1tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sem1tActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sem1tActionPerformed

    private void sem1t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sem1t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sem1t2ActionPerformed

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
       dashboard p=new dashboard();
        p.setVisible(true);
          dispose();
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
            sem4 p=new sem4();
        p.setVisible(true);
          dispose();
    }//GEN-LAST:event_jLabel21MouseClicked

    private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_checkActionPerformed

    private void checkStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_checkStateChanged

    private void dcp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dcp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dcp1ActionPerformed

    private void ca1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ca1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ca1ActionPerformed

    private void esdm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esdm1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_esdm1ActionPerformed

    private void oopl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oopl1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oopl1ActionPerformed

    private void dbmsl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbmsl1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dbmsl1ActionPerformed

    private void dcpl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dcpl1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dcpl1ActionPerformed

    private void dbms1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbms1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dbms1ActionPerformed

    private void oop1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oop1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oop1ActionPerformed

    private void dcp1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dcp1FocusLost
        // TODO add your handling code here:
      
    }//GEN-LAST:event_dcp1FocusLost

    private void oop1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_oop1FocusLost
        // TODO add your handling code here:
    
    }//GEN-LAST:event_oop1FocusLost

    private void ca1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ca1FocusLost
        // TODO add your handling code here:
   
    }//GEN-LAST:event_ca1FocusLost

    private void dbms1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dbms1FocusLost
        // TODO add your handling code here:
     
    }//GEN-LAST:event_dbms1FocusLost

    private void esdm1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_esdm1FocusLost
        // TODO add your handling code here:
    
    }//GEN-LAST:event_esdm1FocusLost

    private void dcpl1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dcpl1FocusLost
        // TODO add your handling code here:
   
    }//GEN-LAST:event_dcpl1FocusLost

    private void oopl1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_oopl1FocusLost
        // TODO add your handling code here:
    
    }//GEN-LAST:event_oopl1FocusLost

    private void dbmsl1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dbmsl1FocusLost
        // TODO add your handling code here:
   
    }//GEN-LAST:event_dbmsl1FocusLost

    private void dcp1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dcp1KeyReleased
        // TODO add your handling code here:
   String grade = dcp1.getText();
int score = GradeConverter.convert(grade);
dcp.setText(Integer.toString(score));
       
    }//GEN-LAST:event_dcp1KeyReleased

    private void oop1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_oop1KeyReleased
        // TODO add your handling code here:
      String grade = oop1.getText();
int score = GradeConverter.convert(grade);
oop.setText(Integer.toString(score));
    }//GEN-LAST:event_oop1KeyReleased

    private void ca1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ca1KeyReleased
        // TODO add your handling code here:
       String grade = ca1.getText();
int score = GradeConverter.convert(grade);
ca.setText(Integer.toString(score));
    }//GEN-LAST:event_ca1KeyReleased

    private void dbms1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dbms1KeyReleased
        // TODO add your handling code here:
     String grade = dbms1.getText();
int score = GradeConverter.convert(grade);
dbms.setText(Integer.toString(score));
    }//GEN-LAST:event_dbms1KeyReleased

    private void esdm1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_esdm1KeyReleased
        // TODO add your handling code here:
       String grade = esdm1.getText();
int score = GradeConverter.convert(grade);
esdm.setText(Integer.toString(score));
    }//GEN-LAST:event_esdm1KeyReleased

    private void dcpl1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dcpl1KeyReleased
        // TODO add your handling code here:
       String grade = dcpl1.getText();
int score = GradeConverter.convert(grade);
dcpl.setText(Integer.toString(score));
    }//GEN-LAST:event_dcpl1KeyReleased

    private void oopl1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_oopl1KeyReleased
        // TODO add your handling code here:
       String grade = oopl1.getText();
int score = GradeConverter.convert(grade);
oopl.setText(Integer.toString(score));
    }//GEN-LAST:event_oopl1KeyReleased

    private void dbmsl1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dbmsl1KeyReleased
        // TODO add your handling code here:
       String grade = dbmsl1.getText();
int score = GradeConverter.convert(grade);
dbmsl.setText(Integer.toString(score));
    }//GEN-LAST:event_dbmsl1KeyReleased

    private void checkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkMouseClicked
        // TODO add your handling code here:
             if(check.isSelected()){
             sem1t.setVisible(false);
               sem1t2.setVisible(false);
                sem1tl.setVisible(false);
                sem1t2l.setVisible(false);
                try{
                 Connection con=Database.connect();
                String sql="UPDATE tbl_main SET checkbox=1 WHERE username='"+Login.username+"'";
                System.out.println(sql);
                Statement stmt=con.createStatement();
                int rs = stmt.executeUpdate(sql);

            }
            catch(Exception e)
            {
                System.out.println("error" + e);
            }
                  
        }
    else{
               sem1t.setVisible(true);
               sem1t2.setVisible(true);
                  sem1tl.setVisible(true);
                sem1t2l.setVisible(true);
                 try{
                Connection con=Database.connect();
                String sql="UPDATE tbl_main SET checkbox=0 WHERE username='"+Login.username+"'";
                System.out.println(sql);
                Statement stmt=con.createStatement();
                int rs = stmt.executeUpdate(sql);

            }
            catch(Exception e)
            {
                System.out.println("error" + e);
            }
          }
          

    }//GEN-LAST:event_checkMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sem1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sem1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sem1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sem1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sem3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cgpa1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField ca;
    private javax.swing.JTextField ca1;
    private javax.swing.JCheckBox check;
    private javax.swing.JTextField dbms;
    private javax.swing.JTextField dbms1;
    private javax.swing.JTextField dbmsl;
    private javax.swing.JTextField dbmsl1;
    private javax.swing.JTextField dcp;
    private javax.swing.JTextField dcp1;
    private javax.swing.JTextField dcpl;
    private javax.swing.JTextField dcpl1;
    private javax.swing.JTextField esdm;
    private javax.swing.JTextField esdm1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JButton jToggleButton1;
    private javax.swing.JTextField oop;
    private javax.swing.JTextField oop1;
    private javax.swing.JTextField oopl;
    private javax.swing.JTextField oopl1;
    private javax.swing.JLabel perc;
    private javax.swing.JLabel percentage1;
    private javax.swing.JProgressBar progress;
    private javax.swing.JTextField sem1t;
    private javax.swing.JTextField sem1t2;
    private javax.swing.JLabel sem1t2l;
    private javax.swing.JLabel sem1tl;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
