

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ACER
 */
public class sem4 extends javax.swing.JFrame {
int value;
    /**
     * Creates new form sem1
     */
    public sem4() {
         initComponents();
         perc.setVisible(false);
       
          setExtendedState(JFrame.MAXIMIZED_BOTH);
      try{
             Connection con=Database.connect();
            String sql="SELECT checkbox FROM tbl_main WHERE username='"+Login.username+"'";
            
            System.out.println(sql);
            Statement stmt=con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            
            if(rs.next())
            {
    int id = rs.getInt("checkbox");
   value = id;
 
            }
        }
        catch(Exception e)
        {
            System.out.println("error" + e);
        }
      if(value == 1){
          
 sem1t.setVisible(false);
  sem1t2.setVisible(false);
  sem1tl.setVisible(false);
  sem1t2l.setVisible(false);
  try{
             Connection con=Database.connect();
            String sql="SELECT sem3_pl FROM tbl_main WHERE username='"+Login.username+"'";
            
            System.out.println(sql);
            Statement stmt=con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            
            if(rs.next())
            {
    int id = rs.getInt("sem3_pl");
    String s=String.valueOf(id);
          sem1t3.setText(s);
            }
        }
        catch(Exception e)
        {
            System.out.println("error" + e);
        }
      }
      else {
         try{
            Connection con=Database.connect();
            String sql="SELECT sem1_p FROM tbl_main WHERE username='"+Login.username+"'";
            
            System.out.println(sql);
            Statement stmt=con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            
            if(rs.next())
            {
    int id = rs.getInt("sem1_p");
    String s=String.valueOf(id);
          sem1t.setText(s);
            }
        }
        catch(Exception e)
        {
            System.out.println("error" + e);
        }

    
         try{
            Connection con=Database.connect();
            String sql="SELECT sem2_p FROM tbl_main WHERE username='"+Login.username+"'";
            
            System.out.println(sql);
            Statement stmt=con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            
            if(rs.next())
            {
    int id = rs.getInt("sem2_p");
    String s=String.valueOf(id);
          sem1t2.setText(s);
            }
        }
        catch(Exception e)
        {
            System.out.println("error" + e);
        }

    
         try{
                      Connection con=Database.connect();

            String sql="SELECT sem3_p FROM tbl_main WHERE username='"+Login.username+"'";
            
            System.out.println(sql);
            Statement stmt=con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            
            if(rs.next())
            {
    int id = rs.getInt("sem3_p");
    String s=String.valueOf(id);
          sem1t3.setText(s);
            }
        }
        catch(Exception e)
        {
            System.out.println("error" + e);
        }
      }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        perc = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        dc1 = new javax.swing.JTextField();
        ad1 = new javax.swing.JTextField();
        cshl1 = new javax.swing.JTextField();
        dsl1 = new javax.swing.JTextField();
        sa1 = new javax.swing.JTextField();
        csh1 = new javax.swing.JTextField();
        ds1 = new javax.swing.JTextField();
        os1 = new javax.swing.JTextField();
        progress = new javax.swing.JProgressBar();
        jLabel21 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        sem1t3 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        sem1t2 = new javax.swing.JTextField();
        sem1t2l = new javax.swing.JLabel();
        sem1tl = new javax.swing.JLabel();
        sem1t = new javax.swing.JTextField();
        cshl = new javax.swing.JTextField();
        ad = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        os = new javax.swing.JTextField();
        dc = new javax.swing.JTextField();
        ds = new javax.swing.JTextField();
        csh = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        sa = new javax.swing.JTextField();
        dsl = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JButton();
        Cgpa = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        percentage1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 708));
        jPanel1.setLayout(null);

        perc.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        perc.setForeground(new java.awt.Color(255, 255, 255));
        perc.setText("%");
        jPanel1.add(perc);
        perc.setBounds(990, 350, 50, 60);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText(" Grade");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(410, 160, 40, 16);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("  Point");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(470, 160, 40, 16);

        dc1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dc1FocusLost(evt);
            }
        });
        dc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dc1ActionPerformed(evt);
            }
        });
        dc1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dc1KeyReleased(evt);
            }
        });
        jPanel1.add(dc1);
        dc1.setBounds(410, 190, 40, 30);

        ad1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ad1FocusLost(evt);
            }
        });
        ad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad1ActionPerformed(evt);
            }
        });
        ad1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ad1KeyReleased(evt);
            }
        });
        jPanel1.add(ad1);
        ad1.setBounds(410, 580, 40, 30);

        cshl1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cshl1FocusLost(evt);
            }
        });
        cshl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cshl1ActionPerformed(evt);
            }
        });
        cshl1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cshl1KeyReleased(evt);
            }
        });
        jPanel1.add(cshl1);
        cshl1.setBounds(410, 520, 40, 30);

        dsl1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dsl1FocusLost(evt);
            }
        });
        dsl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dsl1ActionPerformed(evt);
            }
        });
        dsl1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dsl1KeyReleased(evt);
            }
        });
        jPanel1.add(dsl1);
        dsl1.setBounds(410, 460, 40, 30);

        sa1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                sa1FocusLost(evt);
            }
        });
        sa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sa1ActionPerformed(evt);
            }
        });
        sa1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sa1KeyReleased(evt);
            }
        });
        jPanel1.add(sa1);
        sa1.setBounds(410, 400, 40, 30);

        csh1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                csh1FocusLost(evt);
            }
        });
        csh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csh1ActionPerformed(evt);
            }
        });
        csh1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                csh1KeyReleased(evt);
            }
        });
        jPanel1.add(csh1);
        csh1.setBounds(410, 350, 40, 30);

        ds1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ds1FocusLost(evt);
            }
        });
        ds1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ds1ActionPerformed(evt);
            }
        });
        ds1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ds1KeyReleased(evt);
            }
        });
        jPanel1.add(ds1);
        ds1.setBounds(410, 300, 40, 30);

        os1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                os1FocusLost(evt);
            }
        });
        os1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                os1ActionPerformed(evt);
            }
        });
        os1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                os1KeyReleased(evt);
            }
        });
        jPanel1.add(os1);
        os1.setBounds(410, 250, 40, 30);

        progress.setMaximum(10);
        progress.setToolTipText("Your Progress");
        jPanel1.add(progress);
        progress.setBounds(630, 590, 270, 10);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NEXT2.png"))); // NOI18N
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel21);
        jLabel21.setBounds(1240, 10, 119, 63);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BACK2.png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel16);
        jLabel16.setBounds(10, 10, 120, 63);

        sem1t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sem1t3ActionPerformed(evt);
            }
        });
        jPanel1.add(sem1t3);
        sem1t3.setBounds(750, 230, 100, 40);

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("SEM3 GRADE POINTS:");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(560, 230, 190, 40);

        sem1t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sem1t2ActionPerformed(evt);
            }
        });
        jPanel1.add(sem1t2);
        sem1t2.setBounds(1090, 160, 100, 40);

        sem1t2l.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sem1t2l.setForeground(new java.awt.Color(255, 255, 255));
        sem1t2l.setText("SEM2 GRADE POINTS:");
        jPanel1.add(sem1t2l);
        sem1t2l.setBounds(900, 160, 180, 40);

        sem1tl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sem1tl.setForeground(new java.awt.Color(255, 255, 255));
        sem1tl.setText("SEM1 GRADE POINTS:");
        jPanel1.add(sem1tl);
        sem1tl.setBounds(560, 160, 190, 40);

        sem1t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sem1tActionPerformed(evt);
            }
        });
        jPanel1.add(sem1t);
        sem1t.setBounds(750, 160, 100, 40);

        cshl.setEditable(false);
        cshl.setFocusable(false);
        cshl.setRequestFocusEnabled(false);
        cshl.setVerifyInputWhenFocusTarget(false);
        cshl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cshlActionPerformed(evt);
            }
        });
        jPanel1.add(cshl);
        cshl.setBounds(470, 520, 40, 30);

        ad.setEditable(false);
        ad.setFocusable(false);
        ad.setRequestFocusEnabled(false);
        ad.setVerifyInputWhenFocusTarget(false);
        ad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adActionPerformed(evt);
            }
        });
        jPanel1.add(ad);
        ad.setBounds(470, 580, 40, 30);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Application Development Using Java :");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(100, 560, 310, 70);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Data Communication :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(230, 180, 180, 60);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("         Operating Systems :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(200, 250, 210, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" Data Structures :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(270, 280, 140, 70);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("   Computer System Hardware Lab :");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(120, 500, 290, 80);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Computer System Hardware :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(170, 340, 240, 50);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("System Administration Lab :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(180, 370, 230, 90);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Data Structures Lab :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(240, 430, 180, 90);

        os.setEditable(false);
        os.setFocusable(false);
        os.setRequestFocusEnabled(false);
        os.setVerifyInputWhenFocusTarget(false);
        os.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                osActionPerformed(evt);
            }
        });
        jPanel1.add(os);
        os.setBounds(470, 250, 40, 30);

        dc.setEditable(false);
        dc.setFocusable(false);
        dc.setRequestFocusEnabled(false);
        dc.setVerifyInputWhenFocusTarget(false);
        dc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dcActionPerformed(evt);
            }
        });
        jPanel1.add(dc);
        dc.setBounds(470, 190, 40, 30);

        ds.setEditable(false);
        ds.setFocusable(false);
        ds.setRequestFocusEnabled(false);
        ds.setVerifyInputWhenFocusTarget(false);
        ds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dsActionPerformed(evt);
            }
        });
        jPanel1.add(ds);
        ds.setBounds(470, 300, 40, 30);

        csh.setEditable(false);
        csh.setFocusable(false);
        csh.setRequestFocusEnabled(false);
        csh.setVerifyInputWhenFocusTarget(false);
        csh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cshActionPerformed(evt);
            }
        });
        jPanel1.add(csh);
        csh.setBounds(470, 350, 40, 30);

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("SEMESTER 4");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(560, 20, 280, 70);

        sa.setEditable(false);
        sa.setFocusable(false);
        sa.setRequestFocusEnabled(false);
        sa.setVerifyInputWhenFocusTarget(false);
        sa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saActionPerformed(evt);
            }
        });
        jPanel1.add(sa);
        sa.setBounds(470, 400, 40, 30);

        dsl.setEditable(false);
        dsl.setFocusable(false);
        dsl.setRequestFocusEnabled(false);
        dsl.setVerifyInputWhenFocusTarget(false);
        dsl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dslActionPerformed(evt);
            }
        });
        jPanel1.add(dsl);
        dsl.setBounds(470, 460, 40, 30);

        jToggleButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jToggleButton1.setText("CALCULATE");
        jToggleButton1.setToolTipText("Click to Calculate Your SEM CGPA");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1);
        jToggleButton1.setBounds(660, 520, 210, 50);

        Cgpa.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        Cgpa.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Cgpa);
        Cgpa.setBounds(870, 430, 120, 50);

        total.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        total.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(total);
        total.setBounds(860, 280, 260, 60);

        percentage1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        percentage1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(percentage1);
        percentage1.setBounds(870, 350, 120, 60);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("GRADE POINTS:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(590, 270, 270, 80);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(" CGPA :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(740, 420, 140, 70);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("  PERCENTAGE :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(600, 330, 270, 100);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SEM.png"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, 0, 1370, 710);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void osActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_osActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_osActionPerformed

    private void dcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dcActionPerformed

    private void dsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dsActionPerformed

    private void cshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cshActionPerformed

    private void saActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saActionPerformed

    private void dslActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dslActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dslActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
         if(dc1.getText().isEmpty()||os1.getText().isEmpty()||ds1.getText().isEmpty()||csh1.getText().isEmpty()||sa1.getText().isEmpty()||dsl1.getText().isEmpty()||cshl1.getText().isEmpty()||ad1.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Fill Grades correctly");
      }
      else{
        if(value == 1){
             String dcH, osH, dsH, cshH, saH, dslH, cshlH, adH, sem3tL;
        float average;
       float totalmark;
       float totalmark2;
       double percentage;
        float cgpa;
         float cgpa2;
        
        dcH = dc.getText();
        osH = os.getText();
        dsH = ds.getText();
        cshH = csh.getText();
     
        saH = sa.getText();
      
        dslH = dsl.getText();
    cshlH = cshl.getText();
    
    adH = ad.getText();
   
              sem3tL = sem1t3.getText();
    
        float dcgrade =Float.parseFloat(dcH);
        float osgrade = Float.parseFloat(osH);
        float dsgrade = Float.parseFloat(dsH);
        float cshgrade = Float.parseFloat(cshH);
      
        float sagrade = Float.parseFloat(saH);
     
        float dslgrade = Float.parseFloat(dslH);
        float cshlgrade = Float.parseFloat(cshlH);
        float adgrade = Float.parseFloat(adH);
      
           float sem1tH3 = Float.parseFloat(sem3tL);

        totalmark = ((dcgrade*4) + (osgrade*4) + (dsgrade*5) + (cshgrade*4) + (sagrade*3) + (dslgrade*3) + (cshlgrade*3) + (adgrade*5));
       
        cgpa = (((dcgrade*4) + (osgrade*4) + (dsgrade*5) + (cshgrade*4) + (sagrade*3) + (dslgrade*3) + (cshlgrade*3) + (adgrade*5)) / 31);
        
  totalmark2 = (totalmark + sem1tH3);
  cgpa2 = (totalmark2 / 60);
   percentage = (cgpa2*9.5);
   double rounded = Math.round(cgpa2*100)/100.0;
    double rgpa = Math.round(cgpa2*100)/100.0;
   
         double rounded2 = Math.round(percentage*100)/100.0;
        Cgpa.setText(rounded+"");

        total.setText(totalmark+"");
        percentage1.setText(rounded2+"");
          String cgpA = Cgpa.getText();
        System.out.println(cgpA);
    try{
                          Connection con=Database.connect();

                String sql="UPDATE tbl_main SET tot_cgpal=('"+cgpA+"') WHERE username='"+Login.username+"'";
                System.out.println(sql);
                Statement stmt=con.createStatement();
                int rs = stmt.executeUpdate(sql);

            }
            catch(Exception e)
            {
                System.out.println("error" + e);
            }
           
            perc.setVisible(true);
             int j = (int) cgpa2;
     
   
        progress.setValue(j);  
     
               String sem1tot = total.getText();
        System.out.println(sem1tot);
   try{
                           Connection con=Database.connect();

                String sql="UPDATE tbl_main SET sem4_pl=('"+sem1tot+"') WHERE username='"+Login.username+"'";
                System.out.println(sql);
                Statement stmt=con.createStatement();
                int rs = stmt.executeUpdate(sql);

            }
            catch(Exception e)
            {
                System.out.println("error" + e);
            }
    try{
                            Connection con=Database.connect();

                String sql="UPDATE tbl_main SET tot_pl = sem3_pl+sem4_pl where username='"+Login.username+"'";
                System.out.println(sql);
                Statement stmt=con.createStatement();
                int rs = stmt.executeUpdate(sql);

            }
            catch(Exception e)
            {
                System.out.println("error" + e);
            }
        }
        else{
            String dcH, osH, dsH, cshH, saH, dslH, cshlH, adH, sem1tL, sem2tL, sem3tL;
        float average;
       float totalmark;
       float totalmark2;
       double percentage;
        float cgpa;
         float cgpa2;
        
        dcH = dc.getText();
        osH = os.getText();
        dsH = ds.getText();
        cshH = csh.getText();
     
        saH = sa.getText();
      
        dslH = dsl.getText();
    cshlH = cshl.getText();
    
    adH = ad.getText();
      sem1tL = sem1t.getText();
              sem2tL = sem1t2.getText();
              sem3tL = sem1t3.getText();
    
        float dcgrade =Float.parseFloat(dcH);
        float osgrade = Float.parseFloat(osH);
        float dsgrade = Float.parseFloat(dsH);
        float cshgrade = Float.parseFloat(cshH);
      
        float sagrade = Float.parseFloat(saH);
     
        float dslgrade = Float.parseFloat(dslH);
        float cshlgrade = Float.parseFloat(cshlH);
        float adgrade = Float.parseFloat(adH);
         float sem1tH = Float.parseFloat(sem1tL);
          float sem1tH2 = Float.parseFloat(sem2tL);
           float sem1tH3 = Float.parseFloat(sem3tL);

        totalmark = ((dcgrade*4) + (osgrade*4) + (dsgrade*5) + (cshgrade*4) + (sagrade*3) + (dslgrade*3) + (cshlgrade*3) + (adgrade*5));
       
        cgpa = (((dcgrade*4) + (osgrade*4) + (dsgrade*5) + (cshgrade*4) + (sagrade*3) + (dslgrade*3) + (cshlgrade*3) + (adgrade*5)) / 31);
        
  totalmark2 = (sem1tH + totalmark + sem1tH2 + sem1tH3);
  cgpa2 = (totalmark2 / 115);
   percentage = (cgpa2*9.5);
   double rounded = Math.round(cgpa2*100)/100.0;
   double rgpa = Math.round(cgpa*100)/100.0;
         double rounded2 = Math.round(percentage*100)/100.0;
        Cgpa.setText(rounded+"");
  
        total.setText(totalmark+"");
        percentage1.setText(rounded2+"");
          String cgpA = Cgpa.getText();
        System.out.println(cgpA);
    try{
                           Connection con=Database.connect();

                String sql="UPDATE tbl_main SET tot_cgpa=('"+cgpA+"') WHERE username='"+Login.username+"'";
                System.out.println(sql);
                Statement stmt=con.createStatement();
                int rs = stmt.executeUpdate(sql);

            }
            catch(Exception e)
            {
                System.out.println("error" + e);
            }
           
            perc.setVisible(true);
             int j = (int) cgpa2;
     
   
        progress.setValue(j);  
     
               String sem1tot = total.getText();
        System.out.println(sem1tot);
   try{
                          Connection con=Database.connect();

                String sql="UPDATE tbl_main SET sem4_p=('"+sem1tot+"') WHERE username='"+Login.username+"'";
                System.out.println(sql);
                Statement stmt=con.createStatement();
                int rs = stmt.executeUpdate(sql);

            }
            catch(Exception e)
            {
                System.out.println("error" + e);
            }
   
 try{
                            Connection con=Database.connect();

                String sql="UPDATE tbl_main SET tot_p = sem1_p+sem2_p+sem3_p+sem4_p where username='"+Login.username+"'";
                System.out.println(sql);
                Statement stmt=con.createStatement();
                int rs = stmt.executeUpdate(sql);

            }
            catch(Exception e)
            {
                System.out.println("error" + e);
            }
        }
         }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void cshlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cshlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cshlActionPerformed

    private void adActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adActionPerformed

    private void sem1tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sem1tActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sem1tActionPerformed

    private void sem1t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sem1t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sem1t2ActionPerformed

    private void sem1t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sem1t3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sem1t3ActionPerformed

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        dashboard p=new dashboard();
        p.setVisible(true);
          dispose();
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
         sem5 p=new sem5();
        p.setVisible(true);
          dispose();
    }//GEN-LAST:event_jLabel21MouseClicked

    private void dc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dc1ActionPerformed

    private void ad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ad1ActionPerformed

    private void cshl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cshl1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cshl1ActionPerformed

    private void dsl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dsl1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dsl1ActionPerformed

    private void sa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sa1ActionPerformed

    private void csh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csh1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_csh1ActionPerformed

    private void ds1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ds1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ds1ActionPerformed

    private void os1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_os1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_os1ActionPerformed

    private void dc1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dc1FocusLost
        // TODO add your handling code here:
  
    }//GEN-LAST:event_dc1FocusLost

    private void os1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_os1FocusLost
        // TODO add your handling code here:
    
    }//GEN-LAST:event_os1FocusLost

    private void ds1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ds1FocusLost
        // TODO add your handling code here:
      
    }//GEN-LAST:event_ds1FocusLost

    private void csh1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_csh1FocusLost
        // TODO add your handling code here:
     
    }//GEN-LAST:event_csh1FocusLost

    private void sa1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sa1FocusLost
        // TODO add your handling code here:
     
    }//GEN-LAST:event_sa1FocusLost

    private void dsl1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dsl1FocusLost
        // TODO add your handling code here:
     
    }//GEN-LAST:event_dsl1FocusLost

    private void cshl1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cshl1FocusLost
        // TODO add your handling code here:
    
    }//GEN-LAST:event_cshl1FocusLost

    private void ad1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ad1FocusLost
        // TODO add your handling code here:
     
    }//GEN-LAST:event_ad1FocusLost

    private void dc1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dc1KeyReleased
        // TODO add your handling code here:
                                                      String i;
        i=dc1.getText();
        
        if("S".equals(i) || "s".equals(i)){
           
           dc.setText("10");
        }
      else if("A".equals(i)||"a".equals(i)){
            
           dc.setText("9");
        }
               else if("B".equals(i)||"b".equals(i)){
            
           dc.setText("8");
        }
                   else if("C".equals(i) ||"c".equals(i)){
            
           dc.setText("7");
        }
                       else if("D".equals(i)||"d".equals(i)){
            
           dc.setText("6");
        }
                           else if("E".equals(i)||"e".equals(i)){
            
           dc.setText("5");
        }
                               else if("F".equals(i)||"f".equals(i)){
          
           dc.setText("0");
        }else{
                                    
                               }
     
    }//GEN-LAST:event_dc1KeyReleased

    private void os1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_os1KeyReleased
        // TODO add your handling code here:
                                                    String i;
        i=os1.getText();
        
        if("S".equals(i) || "s".equals(i)){
           
           os.setText("10");
        }
      else if("A".equals(i)||"a".equals(i)){
            
           os.setText("9");
        }
               else if("B".equals(i)||"b".equals(i)){
            
           os.setText("8");
        }
                   else if("C".equals(i) ||"c".equals(i)){
            
           os.setText("7");
        }
                       else if("D".equals(i)||"d".equals(i)){
            
           os.setText("6");
        }
                           else if("E".equals(i)||"e".equals(i)){
            
           os.setText("5");
        }
                               else if("F".equals(i)||"f".equals(i)){
          
           os.setText("0");
        }else{
                                    
                               }
      
    }//GEN-LAST:event_os1KeyReleased

    private void ds1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ds1KeyReleased
        // TODO add your handling code here:
                                                  String i;
        i=ds1.getText();
        
        if("S".equals(i) || "s".equals(i)){
           
           ds.setText("10");
        }
      else if("A".equals(i)||"a".equals(i)){
            
           ds.setText("9");
        }
               else if("B".equals(i)||"b".equals(i)){
            
           ds.setText("8");
        }
                   else if("C".equals(i) ||"c".equals(i)){
            
           ds.setText("7");
        }
                       else if("D".equals(i)||"d".equals(i)||"d".equals(i)){
            
           ds.setText("6");
        }
                           else if("E".equals(i)||"e".equals(i)){
            
           ds.setText("5");
        }
                               else if("F".equals(i)||"f".equals(i)){
          
           ds.setText("0");
        }else{
                                    
                               }
       
    }//GEN-LAST:event_ds1KeyReleased

    private void csh1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_csh1KeyReleased
        // TODO add your handling code here:
                                                   String i;
        i=csh1.getText();
        
        if("S".equals(i) || "s".equals(i)){
           
           csh.setText("10");
        }
      else if("A".equals(i)||"a".equals(i)){
            
           csh.setText("9");
        }
               else if("B".equals(i)||"b".equals(i)){
            
           csh.setText("8");
        }
                   else if("C".equals(i) ||"c".equals(i)){
            
           csh.setText("7");
        }
                       else if("D".equals(i)||"d".equals(i)){
            
           csh.setText("6");
        }
                           else if("E".equals(i)||"e".equals(i)||"e".equals(i)){
            
           csh.setText("5");
        }
                               else if("F".equals(i)||"f".equals(i)){
          
           csh.setText("0");
        }else{
                                    
                               }
      
    }//GEN-LAST:event_csh1KeyReleased

    private void sa1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sa1KeyReleased
        // TODO add your handling code here:
                                                   String i;
        i=sa1.getText();
        
        if("S".equals(i) || "s".equals(i)){
           
          sa.setText("10");
        }
      else if("A".equals(i)||"a".equals(i)){
            
           sa.setText("9");
        }
               else if("B".equals(i)||"b".equals(i)){
            
           sa.setText("8");
        }
                   else if("C".equals(i) ||"c".equals(i)){
            
           sa.setText("7");
        }
                       else if("D".equals(i)||"d".equals(i)){
            
           sa.setText("6");
        }
                           else if("E".equals(i)||"e".equals(i)){
            
          sa.setText("5");
        }
                               else if("F".equals(i)||"f".equals(i)){
          
         sa.setText("0");
        }else{
                                    
                               }
   
       
    }//GEN-LAST:event_sa1KeyReleased

    private void dsl1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dsl1KeyReleased
        // TODO add your handling code here:
                                                   String i;
        i=dsl1.getText();
        
        if("S".equals(i) || "s".equals(i)){
           
           dsl.setText("10");
        }
      else if("A".equals(i)||"a".equals(i)){
            
           dsl.setText("9");
        }
               else if("B".equals(i)||"b".equals(i)){
            
          dsl.setText("8");
        }
                   else if("C".equals(i) ||"c".equals(i)){
            
          dsl.setText("7");
        }
                       else if("D".equals(i)||"d".equals(i)){
            
         dsl.setText("6");
        }
                           else if("E".equals(i)||"e".equals(i)){
            
         dsl.setText("5");
        }
                               else if("F".equals(i)||"f".equals(i)){
          
         dsl.setText("0");
        }else{
                                    
                               }
       
    }//GEN-LAST:event_dsl1KeyReleased

    private void cshl1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cshl1KeyReleased
        // TODO add your handling code here:
                                                    String i;
        i=cshl1.getText();
        
        if("S".equals(i) || "s".equals(i)){
           
           cshl.setText("10");
        }
      else if("A".equals(i)||"a".equals(i)){
            
           cshl.setText("9");
        }
               else if("B".equals(i)||"b".equals(i)){
            
           cshl.setText("8");
        }
                   else if("C".equals(i) ||"c".equals(i)){
            
          cshl.setText("7");
        }
                       else if("D".equals(i)||"d".equals(i)){
            
          cshl.setText("6");
        }
                           else if("E".equals(i)||"e".equals(i)){
            
          cshl.setText("5");
        }
                               else if("F".equals(i)||"f".equals(i)){
          
          cshl.setText("0");
        }
        else{
                                    
                               }
     
    }//GEN-LAST:event_cshl1KeyReleased

    private void ad1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ad1KeyReleased
        // TODO add your handling code here:
                                                   String i;
        i=ad1.getText();
        
        if("S".equals(i) || "s".equals(i)){
           
           ad.setText("10");
        }
      else if("A".equals(i)||"a".equals(i)){
            
           ad.setText("9");
        }
               else if("B".equals(i)||"b".equals(i)){
            
           ad.setText("8");
        }
                   else if("C".equals(i) ||"c".equals(i)){
            
          ad.setText("7");
        }
                       else if("D".equals(i)||"d".equals(i)){
            
         ad.setText("6");
        }
                           else if("E".equals(i)||"e".equals(i)){
            
           ad.setText("5");
        }
                               else if("F".equals(i)||"f".equals(i)){
          
          ad.setText("0");
        }
        else{
                                    
                               }
    
    }//GEN-LAST:event_ad1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sem1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sem1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sem1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sem1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sem4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cgpa;
    private javax.swing.JTextField ad;
    private javax.swing.JTextField ad1;
    private javax.swing.JTextField csh;
    private javax.swing.JTextField csh1;
    private javax.swing.JTextField cshl;
    private javax.swing.JTextField cshl1;
    private javax.swing.JTextField dc;
    private javax.swing.JTextField dc1;
    private javax.swing.JTextField ds;
    private javax.swing.JTextField ds1;
    private javax.swing.JTextField dsl;
    private javax.swing.JTextField dsl1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jToggleButton1;
    private javax.swing.JTextField os;
    private javax.swing.JTextField os1;
    private javax.swing.JLabel perc;
    private javax.swing.JLabel percentage1;
    private javax.swing.JProgressBar progress;
    private javax.swing.JTextField sa;
    private javax.swing.JTextField sa1;
    private javax.swing.JTextField sem1t;
    private javax.swing.JTextField sem1t2;
    private javax.swing.JLabel sem1t2l;
    private javax.swing.JTextField sem1t3;
    private javax.swing.JLabel sem1tl;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
